modLoader="javafml" 
loaderVersion="[31,)" 
issueTrackerURL="https://github.com/ThermalWolf/OreandFarming/issues"
[[mods]]
modId="oreandfarming" 
version="0.1.0" 
displayName="OreandFarming"
displayURL="https://github.com/ThermalWolf/OreandFarming" 
logoFile="oreandfarming.png" 
authors="Jmanz7" 
description="This mod adds serveral features that enhance Minecraft Vanilla."

[[dependencies.oreandfarming]]
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.oreandfarming]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
